### ISSUE TITLE
Json deserializer throws exception when API response includes "]" character in string vaule

### ISSUE THREAD

**Issue by toueno** [paypal/paypalhttp_java#17]
### General information

* SDK/Library version: 1.0.3
* Java Version: 8

### Issue description

Json deserializer throws exception when API response includes "]" character in string vaule like the following (address_line_1  is "123 Townse]nd St" string. 

{"id":"0UL79694EE1509942","intent":"CAPTURE","status":"CREATED","purchase_units":[{"reference_id":"PUHF","amount":{"currency_code":"USD","value":"220.00","breakdown":{"item_total":{"currency_code":"USD","value":"180.00"},"shipping":{"currency_code":"USD","value":"20.00"},"handling":{"currency_code":"USD","value":"10.00"},"tax_total":{"currency_code":"USD","value":"20.00"},"shipping_discount":{"currency_code":"USD","value":"10.00"}}},"payee":{"email_address":"toueno_biz@paypal.com","merchant_id":"Q4KN9FAA64Q62"},"description":"Sporting Goods","custom_id":"CUST-HighFashions","soft_descriptor":"HighFashions","items":[{"name":"T-shirt","unit_amount":{"currency_code":"USD","value":"90.00"},"tax":{"currency_code":"USD","value":"10.00"},"quantity":"1","description":"Green XL","sku":"sku01","category":"PHYSICAL_GOODS"},{"name":"Shoes","unit_amount":{"currency_code":"USD","value":"45.00"},"tax":{"currency_code":"USD","value":"5.00"},"quantity":"2","description":"Running, Size 10.5","sku":"sku02","category":"PHYSICAL_GOODS"}],"shipping":{"name":{"full_name":"John Doe"},"address":{_**"address_line_1":"123 Townse]nd St"**_,"address_line_2":"Floor 6","admin_area_2":"San Francisco","admin_area_1":"CA","postal_code":"94107","country_code":"US"}}}],"create_time":"2022-04-27T00:18:03Z","links":[{"href":"https://api.sandbox.paypal.com/v2/checkout/orders/0UL79694EE1509942","rel":"self","method":"GET"},{"href":"https://www.sandbox.paypal.com/checkoutnow?token=0UL79694EE1509942","rel":"approve","method":"GET"},{"href":"https://api.sandbox.paypal.com/v2/checkout/orders/0UL79694EE1509942","rel":"update","method":"PATCH"},{"href":"https://api.sandbox.paypal.com/v2/checkout/orders/0UL79694EE1509942/capture","rel":"capture","method":"POST"}]}

In this case, extractNextObjectToken() method in Json.java incorrectly detects end of list at "]" character in the "123 Townse]nd St" string . As the result, the SDK throws the following exception;

java.lang.ArrayIndexOutOfBoundsException: 1035
        at com.paypal.http.serializer.Json.consumeWhitespace(Json.java:294)
        at com.paypal.http.serializer.Json.splitJsonArray(Json.java:310)
        at com.paypal.http.serializer.Json.deserializeListInternal(Json.java:178)
        at com.paypal.http.serializer.Json.deserializeObjectInternal(Json.java:243)
        at com.paypal.http.serializer.Json.deserializeInternal(Json.java:205)
        at com.paypal.http.serializer.Json.decode(Json.java:69)
        at com.paypal.http.Encoder.deserializeResponse(Encoder.java:95)
        at com.paypal.http.HttpClient.parseResponse(HttpClient.java:194)
        at com.paypal.http.HttpClient.execute(HttpClient.java:98)
        at com.paypal.CaptureIntentExamples.CreateOrder.createOrder(CreateOrder.java:82)
        at com.paypal.CaptureIntentExamples.RunAll.main(RunAll.java:15)

Also I found in case of "[" , the Json deserializer also misunderstands nested lists.

So anyway Json deserializer should ingnor any characters inside string object when detecting tokens.

**Comment by toueno** [comment]
I found the following characters cause the issue (not only "]" )

{

}

[

]
