### ISSUE TITLE
Content-type parsing issue

### ISSUE THREAD

**Issue by xupyprmv** [paypal/paypalhttp_java#7]
### General information

* SDK/Library version: 1.0.0 / 1.0.1
* Java Version: 11

### Issue description

For some reason, starting from yesterday, PayPal API start to return header with partial upper-case mode during call of `GET /v1/payments/payouts/{payout_batch_id}`

> java.io.UnsupportedEncodingException: Unable to decode response with content-type: application/JSON. Supported decodings are: [^application\/json, ^text\/.*, ^multipart\/.*, ^application/x-www-form-urlencoded]
	at com.paypal.http.Encoder.deserializeResponse(Encoder.java:89)
	at com.paypal.http.HttpClient.parseResponse(HttpClient.java:194)
	at com.paypal.http.HttpClient.execute(HttpClient.java:98) 

Serializer is registered in lowercase: https://github.com/paypal/paypalhttp_java/blob/master/paypalhttp/src/main/java/com/paypal/http/serializer/Json.java#L27 and seems it is a reason of issue.

Possible solution: make Encoder serializer extractor case insensitive (for parsing Content-Type): https://github.com/paypal/paypalhttp_java/blob/master/paypalhttp/src/main/java/com/paypal/http/Encoder.java#L116

P.S. I also checked PayPal API calls log and requests are processed well, so it is simply response parsing error.

**Comment by xupyprmv** [comment]
Fixed by https://github.com/paypal/paypalhttp_java/pull/13
